import { sequelize } from './src/models/index.js';

async function upgradeAll() {
  try {
    console.log('--- 🛡️ Upgrading All Tables to Identity System ---');

    const tables = ['users', 'urls', 'clicks'];

    for (const table of tables) {
      console.log(`\nProcessing table: ${table}...`);
      
      // Check if it already is an identity column
      const [columns] = await sequelize.query(`
        SELECT column_name, is_identity
        FROM information_schema.columns
        WHERE table_name = '${table}' AND column_name = 'id';
      `);

      if (columns.length > 0 && columns[0].is_identity === 'YES') {
        console.log(`✅ Table "${table}" already uses Identity.`);
      } else {
        console.log(`🔄 Upgrading "${table}" to Identity...`);
        // Drop existing default
        await sequelize.query(`ALTER TABLE "${table}" ALTER COLUMN "id" DROP DEFAULT;`);
        // Add identity
        await sequelize.query(`ALTER TABLE "${table}" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;`);
        console.log(`✅ Table "${table}" upgraded successfully.`);
      }

      // Sync sequence
      console.log(`📊 Synchronizing sequence for "${table}"...`);
      const [[{ maxId }]] = await sequelize.query(`SELECT MAX(id) as "maxId" FROM "${table}"`);
      const startValue = (maxId || 0) + 1;
      await sequelize.query(`SELECT setval(pg_get_serial_sequence('${table}', 'id'), ${startValue}, false);`);
      console.log(`✅ Sequence for "${table}" set to start at: ${startValue}`);
    }

    console.log('\n--- 🎉 All Upgrades Finished! ---');

  } catch (err) {
    console.error('❌ Upgrade failed:', err.message);
  } finally {
    await sequelize.close();
  }
}

upgradeAll();
